services:
  client:
    build: ./client
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - NODE_ENV=development
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app

  server:
    build: ./server
    ports:
      - 5001:5001
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
