version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    image: client:latest
