"""change the EventInvite class

Revision ID: f40f66d859cc
Revises: 34f20c5184be
Create Date: 2024-08-30 00:51:03.321545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40f66d859cc'
down_revision = '34f20c5184be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invite', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_event_user_invite', ['event_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invite', schema=None) as batch_op:
        batch_op.drop_constraint('unique_event_user_invite', type_='unique')

    # ### end Alembic commands ###
